[package]
name = "osctf-native"
version = "0.1.0"
authors = ["Sam A. Horvath-Hunt <samhh.web@gmail.com>"]

[[bin]]
name = "game-attempt-1"
path = "./src/main.rs"

[dependencies]
"piston_window" = "0.72.0"
"find_folder" = "0.3.0"
"update_rate" = "2.0.0"
