[package]
name = "osctf-native"
version = "0.1.0"
authors = ["Sam A. Horvath-Hunt <samhh.web@gmail.com>"]

[[bin]]
name = "game-attempt-1"
path = "./src/main.rs"

[dependencies]
find_folder = "0.3.0"
# nphysics2d = "0.7.2"
piston_window = "0.72.0"
specs = "0.10.0"
update_rate = "2.0.0"
