[package]
name = "game_attempt_1"
version = "0.1.0"
authors = ["Sam A. Horvath-Hunt <samhh.web@gmail.com>"]

[[bin]]
name = "game-attempt-1"

[dependencies]
"piston_window" = "0.67.0"
"find_folder" = "*"
"update_rate" = "1.1.0"
